// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcSuAWk2BX0R3r3WI0SpzHs120mlqb8Lk',
    appId: '1:499464343677:web:d2bbc6cefb642e03f9a114',
    messagingSenderId: '499464343677',
    projectId: 'fasty-ea533',
    authDomain: 'fasty-ea533.firebaseapp.com',
    storageBucket: 'fasty-ea533.appspot.com',
    measurementId: 'G-NNX2ZL1J1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp3TKac6JLaGkf_3hmXNpWIHmZm-mrAKw',
    appId: '1:499464343677:android:359c35b32eaf4037f9a114',
    messagingSenderId: '499464343677',
    projectId: 'fasty-ea533',
    storageBucket: 'fasty-ea533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw1bkbuERDSWhXjQD6t5sWAN-zYxSzJ54',
    appId: '1:499464343677:ios:cb9e6327c37873fdf9a114',
    messagingSenderId: '499464343677',
    projectId: 'fasty-ea533',
    storageBucket: 'fasty-ea533.appspot.com',
    iosBundleId: 'com.example.fasty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw1bkbuERDSWhXjQD6t5sWAN-zYxSzJ54',
    appId: '1:499464343677:ios:d7a180a3e02a9b08f9a114',
    messagingSenderId: '499464343677',
    projectId: 'fasty-ea533',
    storageBucket: 'fasty-ea533.appspot.com',
    iosBundleId: 'com.achrafapps.fasty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcSuAWk2BX0R3r3WI0SpzHs120mlqb8Lk',
    appId: '1:499464343677:web:06c152359adc99b1f9a114',
    messagingSenderId: '499464343677',
    projectId: 'fasty-ea533',
    authDomain: 'fasty-ea533.firebaseapp.com',
    storageBucket: 'fasty-ea533.appspot.com',
    measurementId: 'G-DPJHX2EZFK',
  );
}
